language: php

php:
  - 5.4
  - 7.6
  - 7.0
  - 7.2.1

env: RUN_PHPCS=1 RUN_CODE_COVERAGE=1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - bash test/bin/phpunit.sh
  - bash test/bin/phpcs.sh