language: php

matrix:
  fast_finish: true
  include:
  - php: 5.3.29
  - php: 5.6
  - php: 7.0
  - php: 7.2.1
    env: RUN_PHPCS=1 RUN_CODE_COVERAGE=1

before_script:
  - bash test/bin/travis.sh before
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - bash test/bin/phpunit.sh
  - bash test/bin/phpcs.sh

after_script:
  - bash tests/bin/travis.sh after