language: php

matrix:
  fast_finish: true
  include:
  - php: 5.3
    dist: precise
  - php: 5.6
  - php: 7.0
  - php: 7.2
    env: RUN_PHPCS=1 RUN_CODE_COVERAGE=1

before_script:
  - bash test/bin/travis.sh
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - bash test/bin/phpunit.sh
  - bash test/bin/phpcs.sh

after_script:
  - if [[ $RUN_CODE_COVERAGE == 1 ]]; then wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar; fi
  - if [[ $RUN_CODE_COVERAGE == 1 ]]; then chmod +x php-coveralls.phar; fi
  - if [[ $RUN_CODE_COVERAGE == 1 ]]; then php php-coveralls.phar -x clover.xml --verbose; fi