language: php

php: 5.4

matrix:
  fast_finish: true
  include:
  - php: 5.6
  - php: 7.0
  - php: 7.2.1
    env: RUN_PHPCS=1 RUN_CODE_COVERAGE=1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - bash test/bin/phpunit.sh
  - bash test/bin/phpcs.sh